server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    password: happy123
    url: jdbc:mysql://localhost:3306/test
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: clientId
            clientSecret: secret
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - email
              - profile
          facebook:
            clientId: clientId
            clientSecret: secret
            redirect-uri: http://localhost:8080/oauth2/callback/facebook
            scope:
              - email
              - public_profile


