spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: asdsd
            clientSecret: asdasd
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - email
              - profile
          facebook:
            clientId: asdasd
            clientSecret: asdasd
            redirect-uri: http://localhost:8080/oauth2/callback/facebook
            scope:
              - email
              - public_profile


